name: Deploy to GCP App Engine

on:
  push:
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GCP App Engine
    runs-on: ubuntu-latest
    environment: env
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy to GCP App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: 'samples/counter-app/app.yaml'
        version: v1
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}