name: Run lint and test on all PR

on:
  pull_request:
    branches:
      - "**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Run lint and test on all PR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup environment
      uses: actions/setup-node@v3
      with:
        node-version: '21.0.0'

    - name: Install dependencies
      working-directory: ./samples/counter-app
      run: |
        npm ci

    - name: Run linter
      working-directory: ./samples/counter-app
      run: |
        npm run lint

    - name: Run testing
      working-directory: ./samples/counter-app
      run: |
        npm run test